services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Only DataFixtures services are allowed in services_test.yaml
  WechatOfficialAccountMenuBundle\DataFixtures\:
    resource: '../../DataFixtures/*'
    tags: ['doctrine.fixture.orm']

  # Test memory user provider
  WechatOfficialAccountMenuBundle\Tests\Test\TestMemoryUserProvider:
    class: WechatOfficialAccountMenuBundle\Tests\Test\TestMemoryUserProvider
    public: true